<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body class="bg-dark">

<div class="container mt-5">

    <div class="row justify-content-center">

        <div class="col-md-4">

            <div class="card p-4">

                <h2 class="text-center mb-4">Iniciar sesión</h2>

                <?php if (isset($_SESSION['error_login'])): ?>
                    <div class="alert alert-danger">
                        <?= $_SESSION['error_login']; ?>
                    </div>
                    <?php unset($_SESSION['error_login']); ?>
                <?php endif; ?>

                <form action="<?= BASE_URL ?>verify" method="POST">

                    <div class="mb-3">
                        <label>Usuario</label>
                        <input type="text" name="usuario" class="form-control" required>
                    </div>

                    <div class="mb-3">
                        <label>Contraseña</label>
                        <input type="password" name="password" class="form-control" required>
                    </div>

                    <button class="btn btn-dark w-100">
                        Entrar
                    </button>

                </form>

            </div>

        </div>

    </div>

</div>

</body>
</html>